# -*- coding: utf-8 -*-
"""Syslog_statics_V2.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1WUmohoChxtTLVV5PHeKSoQtday5ze2Fw
"""
import sys
filename=sys.argv[1]
raw_list=[]
with open(filename+"_classifiedv2.csv") as file:
    for line in file:
        line = line.strip()
        if len(line)!=0:
            raw_list.append(line)
        
    print(len(raw_list))
    print(raw_list[1])

logcount=raw_list[1].split(",")[5]
print(logcount)

item_line = 0
start_line = 1
end_line = 0
onis_reboot = 0
onis_stable = 0
offis_reboot = 0
offis_stable = 0
on_unknown = 0
off_unknown = 0
loop_cnt = 0
end_line_index=[]
raw_list[item_line]=raw_list[item_line]+",onis_reboot,onis_stable,on_unknown,offis_reboot,offis_stable,off_unknown,total_loop"
with open(filename+"_statisticsv2.csv", 'w') as out_f:
  for x in range(start_line, len(raw_list)):
    is_end_index=0
    if raw_list[x].split(",")[0] == "\"" and raw_list[x].split(",")[4] == "":
      on_unknown+=1
      end_line=x
      is_end_index=1
    if raw_list[x].split(",")[0] == "\"" and raw_list[x].split(",")[4] != "":
      if raw_list[x].split(",")[4] == "onis_reboot":
        onis_reboot+=1
        end_line=x
        is_end_index=1
      if raw_list[x].split(",")[4] == "onis_stable":
        onis_stable+=1
        end_line=x
        is_end_index=1
    if raw_list[x].split(",")[0] == "\"" and raw_list[x].split(",")[5] == "":
      off_unknown+=1
      end_line=x
      is_end_index=1
    if raw_list[x].split(",")[0] == "\"" and raw_list[x].split(",")[5] != "":
      if raw_list[x].split(",")[5] == "offis_reboot":
        offis_reboot+=1
        end_line=x
        is_end_index=1
      if raw_list[x].split(",")[5] == "offis_stable":
        offis_stable+=1
        end_line=x  
        is_end_index=1
    if is_end_index == 1:
      #print("###"+str(x))
      end_line_index.append(str(x))
      #print("@@@"+raw_list[end_line])
    start_line = end_line +1
    
  #print(end_line_index)
  loop_cnt =offis_reboot+offis_stable+off_unknown
  print("onre"+str(onis_reboot))
  print("onst"+str(onis_stable))
  print("onun"+str(on_unknown))
  print("offre"+str(offis_reboot))
  print("offst"+str(offis_stable))
  print("offun"+str(off_unknown))
  print("lcnt"+str(loop_cnt))
  raw_list[int(end_line_index[0])]+=","+str(onis_reboot)+","+str(onis_stable)+","+str(on_unknown)+","+str(offis_reboot)+","+str(offis_stable)+","+str(off_unknown)+","+str(loop_cnt)
  print("@@"+raw_list[int(end_line_index[0])])
  for cnt in range(0,len(raw_list)):
      out_f.write(raw_list[cnt]+"\n")
